version: '3.8'

services:
  api-hub:
    image: ghcr.io/lei-rr/api-hub:master
    container_name: api-hub
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
