version: '3.8'

services:
  api-hub:
    image: ghcr.io/lei-rr/api-hub:latest
    container_name: api-hub
    ports:
      - "2020:2020"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
